version: "3.8"

services:
  api:
    restart: always
    ports:
    - 8081:8081
    build:
      context: ./server
      dockerfile: ./Dockerfile
    volumes:
      - ./server:/app/server
    command: npm run dev
    depends_on:
      - mongo
  frontend:
    restart: always
    ports:
      - 3000:3000
    build:
      context: ./client
      dockerfile: ./Dockerfile
    volumes:
      - ./client:/app/client
    depends_on:
      - api
  mongo:
    image: mongo
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - apiDB:/data/db

volumes:
  apiDB:

